"""add_founder_desk_video_field

Revision ID: 94973a9c22a4
Revises: 0b8a80bf9818
Create Date: 2026-06-03 13:52:06.319307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94973a9c22a4'
down_revision: Union[str, Sequence[str], None] = '0b8a80bf9818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_founder_desk', sa.Column('video_youtube_id', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('home_founder_desk', 'video_youtube_id')
    # ### end Alembic commands ###
