"""add_founder_desk_secondary_cta

Revision ID: a929ef25af0d
Revises: 94973a9c22a4
Create Date: 2026-06-03 14:10:30.035052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a929ef25af0d'
down_revision: Union[str, Sequence[str], None] = '94973a9c22a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_founder_desk', sa.Column('secondary_cta_text', sa.String(length=100), nullable=True))
    op.add_column('home_founder_desk', sa.Column('secondary_cta_link', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('home_founder_desk', 'secondary_cta_link')
    op.drop_column('home_founder_desk', 'secondary_cta_text')
    # ### end Alembic commands ###
