"""add_maintenance_bg_image_url

Revision ID: 351b9e24c6ba
Revises: f8e9d0c1a2b3
Create Date: 2026-06-04 04:40:02.665767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '351b9e24c6ba'
down_revision: Union[str, Sequence[str], None] = 'f8e9d0c1a2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('maintenance_bg_image_url', sa.Text(), nullable=True))
    op.alter_column('site_settings', 'maintenance_mode',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site_settings', 'maintenance_mode',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.drop_column('site_settings', 'maintenance_bg_image_url')
    # ### end Alembic commands ###
