"""add_about_alumni_section_and_logo_table

Revision ID: 5c4c2143331f
Revises: b496ccc3eb54
Create Date: 2026-07-23 18:07:46.084213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c4c2143331f'
down_revision: Union[str, Sequence[str], None] = 'b496ccc3eb54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about_settings', sa.Column('alumni_eyebrow', sa.String(length=255), nullable=True))
    op.add_column('about_settings', sa.Column('alumni_title', sa.String(length=500), nullable=True))
    op.add_column('about_settings', sa.Column('alumni_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('about_settings', 'alumni_description')
    op.drop_column('about_settings', 'alumni_title')
    op.drop_column('about_settings', 'alumni_eyebrow')
    # ### end Alembic commands ###
