"""add_about_hero_fields

Revision ID: 53ae74b534dd
Revises: d3e4f5a6b7c8
Create Date: 2026-07-18 02:03:41.712012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ae74b534dd'
down_revision: Union[str, Sequence[str], None] = 'd3e4f5a6b7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about_settings', sa.Column('hero_eyebrow', sa.String(length=255), nullable=True))
    op.add_column('about_settings', sa.Column('hero_title', sa.String(length=500), nullable=True))
    op.add_column('about_settings', sa.Column('hero_subtitle', sa.Text(), nullable=True))
    op.add_column('about_settings', sa.Column('hero_note', sa.String(length=255), nullable=True))
    op.add_column('about_settings', sa.Column('hero_image_1', sa.Text(), nullable=True))
    op.add_column('about_settings', sa.Column('hero_image_2', sa.Text(), nullable=True))
    op.add_column('about_settings', sa.Column('hero_image_3', sa.Text(), nullable=True))
    op.add_column('about_settings', sa.Column('hero_image_4', sa.Text(), nullable=True))
    op.add_column('about_settings', sa.Column('hero_image_5', sa.Text(), nullable=True))
    op.add_column('about_settings', sa.Column('hero_image_6', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('about_settings', 'hero_image_6')
    op.drop_column('about_settings', 'hero_image_5')
    op.drop_column('about_settings', 'hero_image_4')
    op.drop_column('about_settings', 'hero_image_3')
    op.drop_column('about_settings', 'hero_image_2')
    op.drop_column('about_settings', 'hero_image_1')
    op.drop_column('about_settings', 'hero_note')
    op.drop_column('about_settings', 'hero_subtitle')
    op.drop_column('about_settings', 'hero_title')
    op.drop_column('about_settings', 'hero_eyebrow')
    # ### end Alembic commands ###
