"""add_rating_to_home_recent_course_cards

Revision ID: 74a2bd620e25
Revises: 351b9e24c6ba
Create Date: 2026-06-05 14:45:30.569996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a2bd620e25'
down_revision: Union[str, Sequence[str], None] = '351b9e24c6ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_recent_course_cards', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('home_recent_course_cards', 'rating')
    # ### end Alembic commands ###
