"""add teaching_hours and rating to instructors

Revision ID: 38ee638b1c07
Revises: a1b2c3d4e5f6
Create Date: 2026-07-29 03:05:10.687726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ee638b1c07'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructors', sa.Column('teaching_hours', sa.String(length=50), nullable=True))
    op.add_column('instructors', sa.Column('rating', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructors', 'rating')
    op.drop_column('instructors', 'teaching_hours')
    # ### end Alembic commands ###
