"""add_openrouter_fields_to_ai_settings

Revision ID: 06793614fded
Revises: 171399f77096
Create Date: 2026-06-08 04:55:50.440964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06793614fded'
down_revision: Union[str, Sequence[str], None] = '171399f77096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_settings', sa.Column('openrouter_api_key', sa.String(length=500), nullable=True))
    op.add_column('ai_settings', sa.Column('model_exam_text', sa.String(length=255), nullable=True))
    op.add_column('ai_settings', sa.Column('model_image_reply', sa.String(length=255), nullable=True))
    op.add_column('ai_settings', sa.Column('model_video_reply', sa.String(length=255), nullable=True))
    op.add_column('ai_settings', sa.Column('model_file_read', sa.String(length=255), nullable=True))
    op.add_column('ai_settings', sa.Column('model_general_text', sa.String(length=255), nullable=True))
    op.add_column('ai_settings', sa.Column('model_thinking', sa.String(length=255), nullable=True))
    op.add_column('ai_settings', sa.Column('model_live_doubt', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_settings', 'model_live_doubt')
    op.drop_column('ai_settings', 'model_thinking')
    op.drop_column('ai_settings', 'model_general_text')
    op.drop_column('ai_settings', 'model_file_read')
    op.drop_column('ai_settings', 'model_video_reply')
    op.drop_column('ai_settings', 'model_image_reply')
    op.drop_column('ai_settings', 'model_exam_text')
    op.drop_column('ai_settings', 'openrouter_api_key')
    # ### end Alembic commands ###
