"""initial_baseline_all_tables

Revision ID: 8fbbb2dea4a9
Revises:
Create Date: 2026-05-08 14:21:06.431967

─────────────────────────────────────────────────────────
PURPOSE:
  This is a TRACKING baseline — not a CREATE-FROM-SCRATCH migration.
  It was generated by `alembic revision --autogenerate` against an
  already-populated PostgreSQL database and immediately stamped with
  `alembic stamp head`.

FRESH DATABASE SETUP:
  1. Start the FastAPI server → main.py calls Base.metadata.create_all()
     which creates ALL tables from models.py automatically.
  2. Then run: alembic stamp head
     This tells Alembic "the DB is now at this baseline".
  3. All future schema changes go through:
     alembic revision --autogenerate -m "description"
     alembic upgrade head

DO NOT run `alembic upgrade head` on a brand-new empty database
without first starting the server (to create tables via create_all).
─────────────────────────────────────────────────────────
"""
from typing import Sequence, Union
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8fbbb2dea4a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Baseline snapshot — no operations needed.
    Tables are created by Base.metadata.create_all() in main.py on startup.
    Future migrations will apply incremental changes on top of this baseline.
    """
    pass


def downgrade() -> None:
    """
    Baseline snapshot — no downgrade operations.
    """
    pass
