"""add_home_journey_section_and_milestone_tables

Revision ID: 776cd7103882
Revises: b4494a2aac73
Create Date: 2026-06-01 17:02:37.098146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776cd7103882'
down_revision: Union[str, Sequence[str], None] = 'b4494a2aac73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
