"""add_founder_linkedin_and_business_logo_url

Revision ID: b496ccc3eb54
Revises: 7f8e9a0b1c2d
Create Date: 2026-07-23 17:49:48.814125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b496ccc3eb54'
down_revision: Union[str, Sequence[str], None] = '7f8e9a0b1c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about_founder', sa.Column('linkedin_url', sa.Text(), nullable=True))
    op.add_column('about_founder', sa.Column('business_logo_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('about_founder', 'business_logo_url')
    op.drop_column('about_founder', 'linkedin_url')
    # ### end Alembic commands ###
