"""create_navbar_item_table

Revision ID: 69b7f2b51c8c
Revises: a3b4c5d6e7f8
Create Date: 2026-05-31 20:24:33.366301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69b7f2b51c8c'
down_revision: Union[str, Sequence[str], None] = 'a3b4c5d6e7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_theme_settings_id'), table_name='theme_settings')
    op.drop_table('theme_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('primary_color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('secondary_color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('background_color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('text_color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('theme_settings_pkey'))
    )
    op.create_index(op.f('ix_theme_settings_id'), 'theme_settings', ['id'], unique=False)
    # ### end Alembic commands ###
